package org.gongtao.bean;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.departmentid
     *
     * @mbggenerated
     */
    private Integer departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.departmentname
     *
     * @mbggenerated
     */
    private String departmentname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.departmentid
     *
     * @return the value of t_department.departmentid
     *
     * @mbggenerated
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.departmentid
     *
     * @param departmentid the value for t_department.departmentid
     *
     * @mbggenerated
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.departmentname
     *
     * @return the value of t_department.departmentname
     *
     * @mbggenerated
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.departmentname
     *
     * @param departmentname the value for t_department.departmentname
     *
     * @mbggenerated
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname;
    }
}